"""enable on delete set null on article.cluster_id

Revision ID: 2446b9fe23fd
Revises: af4ee713bd84
Create Date: 2025-07-20 15:13:36.631575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2446b9fe23fd'
down_revision: Union[str, Sequence[str], None] = 'af4ee713bd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('article_cluster_id_fkey'), 'article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'cluster', ['cluster_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_foreign_key(op.f('article_cluster_id_fkey'), 'article', 'cluster', ['cluster_id'], ['id'])
    # ### end Alembic commands ###
