"""added image urls to article

Revision ID: 7bef5e692ddd
Revises: fb193cb38c13
Create Date: 2025-07-21 21:53:48.261896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bef5e692ddd'
down_revision: Union[str, Sequence[str], None] = 'fb193cb38c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('image_urls', postgresql.ARRAY(sa.String()), nullable=True))
    op.alter_column('news_provider', 'rank',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_provider', 'rank',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('article', 'image_urls')
    # ### end Alembic commands ###
