"""add slug to cluster

Revision ID: 924de4a72004
Revises: 91757614c256
Create Date: 2025-10-11 14:52:04.869978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924de4a72004'
down_revision: Union[str, Sequence[str], None] = '91757614c256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('slug', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'cluster', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cluster', type_='unique')
    op.drop_column('cluster', 'slug')
    # ### end Alembic commands ###
