"""fix cluster id foreign key on article cluster table

Revision ID: a5ac08e3e84b
Revises: b5775fc5b404
Create Date: 2025-10-30 16:18:42.051372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ac08e3e84b'
down_revision: Union[str, Sequence[str], None] = 'b5775fc5b404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('article_cluster_cluster_id_fkey'), 'article_cluster', type_='foreignkey')
    op.create_foreign_key(None, 'article_cluster', 'cluster_v2', ['cluster_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article_cluster', type_='foreignkey')
    op.create_foreign_key(op.f('article_cluster_cluster_id_fkey'), 'article_cluster', 'cluster', ['cluster_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
