[tool.poetry]
name = "scraper"
version = "0.1.0"
description = ""
authors = ["marko154 <marko.gartnar777@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
crawl4ai = "^0.4.247"
pydantic = "^2.10.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
