"""added run_id index on aritcle_cluster and cluster

Revision ID: 479d12d6c013
Revises: 5afa426bc7c2
Create Date: 2025-12-06 20:06:18.679606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479d12d6c013'
down_revision: Union[str, Sequence[str], None] = '5afa426bc7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_article_cluster_run_id', 'article_cluster', ['run_id'], unique=False)
    op.create_index('ix_cluster_v2_run_id', 'cluster_v2', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cluster_v2_run_id', table_name='cluster_v2')
    op.drop_index('ix_article_cluster_run_id', table_name='article_cluster')
    # ### end Alembic commands ###
