"""added mossData

Revision ID: 5afa426bc7c2
Revises: 73cf0666d085
Create Date: 2025-11-15 17:38:36.420905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5afa426bc7c2'
down_revision: Union[str, Sequence[str], None] = '73cf0666d085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moss_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_key', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('reach_percent', sa.Float(), nullable=False),
    sa.Column('avg_daily_reach', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('avg_session_duration', sa.String(), nullable=False),
    sa.Column('trend', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_key'], ['news_provider.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moss_data')
    # ### end Alembic commands ###
