"""add_cluster_table

Revision ID: 5b2a6b548dff
Revises: 7045cddb9867
Create Date: 2025-07-19 10:01:04.838632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2a6b548dff'
down_revision: Union[str, Sequence[str], None] = '7045cddb9867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column('article', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'cluster', ['cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'cluster_id')
    op.drop_table('cluster')
    # ### end Alembic commands ###
