"""added an llm_rank to the article table, implemented article ranking by llm

Revision ID: 5eda10a83431
Revises: 17a4f4d1b30b
Create Date: 2025-10-07 19:34:49.138098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eda10a83431'
down_revision: Union[str, Sequence[str], None] = '17a4f4d1b30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('llm_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'llm_rank')
    # ### end Alembic commands ###
