"""add published_at, news_provider_key composite index to article

Revision ID: 73cf0666d085
Revises: 94f257bd3493
Create Date: 2025-11-09 18:34:35.267593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73cf0666d085'
down_revision: Union[str, Sequence[str], None] = '94f257bd3493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_published_at'), table_name='article')
    op.create_index('ix_article_published_at_news_provider_key', 'article', ['published_at', 'news_provider_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_article_published_at_news_provider_key', table_name='article')
    op.create_index(op.f('ix_article_published_at'), 'article', ['published_at'], unique=False)
    # ### end Alembic commands ###
