"""add is_paywalled to article

Revision ID: 8de5e3a3e1cf
Revises: a6699cebd74c
Create Date: 2025-11-07 07:41:45.427959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de5e3a3e1cf'
down_revision: Union[str, Sequence[str], None] = 'a6699cebd74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('is_paywalled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'is_paywalled')
    # ### end Alembic commands ###
