"""added bias_rating field to provider schema

Revision ID: 91757614c256
Revises: 5eda10a83431
Create Date: 2025-10-07 22:07:29.019657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91757614c256'
down_revision: Union[str, Sequence[str], None] = '5eda10a83431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_provider', sa.Column('bias_rating', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_provider', 'bias_rating')
    # ### end Alembic commands ###
