"""add indexes

Revision ID: 94f257bd3493
Revises: 8de5e3a3e1cf
Create Date: 2025-11-08 17:52:19.654866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f257bd3493'
down_revision: Union[str, Sequence[str], None] = '8de5e3a3e1cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_article_published_at', 'article', ['published_at'], unique=False)
    op.create_index('ix_article_cluster_cluster_id', 'article_cluster', ['cluster_id'], unique=False)
    op.create_index('ix_cluster_run_created_at', 'cluster_run', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cluster_run_created_at', table_name='cluster_run')
    op.drop_index('ix_article_cluster_cluster_id', table_name='article_cluster')
    op.drop_index('ix_article_published_at', table_name='article')
    # ### end Alembic commands ###
