"""remove title uq constraint on cluster

Revision ID: a779efd6c49b
Revises: 5b2a6b548dff
Create Date: 2025-07-19 10:24:04.459051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a779efd6c49b'
down_revision: Union[str, Sequence[str], None] = '5b2a6b548dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cluster_title_key'), 'cluster', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('cluster_title_key'), 'cluster', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
