"""add run_id to clusterv2 table

Revision ID: f1492fbc5923
Revises: a5ac08e3e84b
Create Date: 2025-10-30 17:03:52.081724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1492fbc5923'
down_revision: Union[str, Sequence[str], None] = 'a5ac08e3e84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_v2', sa.Column('run_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cluster_v2', 'cluster_run', ['run_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cluster_v2', type_='foreignkey')
    op.drop_column('cluster_v2', 'run_id')
    # ### end Alembic commands ###
