"""add rank to news provider

Revision ID: fb193cb38c13
Revises: 2446b9fe23fd
Create Date: 2025-07-20 18:52:58.497860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb193cb38c13'
down_revision: Union[str, Sequence[str], None] = '2446b9fe23fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_provider', sa.Column('rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_provider', 'rank')
    # ### end Alembic commands ###
