# this action does not work, since the ip address of the runner is not whitelisted in the database
# name: Alembic Migration Check on PR

# on: pull_request

# jobs:
#   check-migration:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Check Alembic Migration Version
#         uses: DevGlitch/alembic-migration-checker@v1.1
#         with:
#           db_url: ${{ secrets.DATABASE_URL }} # Format: postgresql+psycopg2://user:password@host:port/dbname
#           migrations_path: ./scraper/alembic/versions/
